/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEthAnchorExchangeRateFeeder,
  IEthAnchorExchangeRateFeederInterface,
} from "../../Fund.sol/IEthAnchorExchangeRateFeeder";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_simulate",
        type: "bool",
      },
    ],
    name: "exchangeRateOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IEthAnchorExchangeRateFeeder__factory {
  static readonly abi = _abi;
  static createInterface(): IEthAnchorExchangeRateFeederInterface {
    return new utils.Interface(_abi) as IEthAnchorExchangeRateFeederInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEthAnchorExchangeRateFeeder {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IEthAnchorExchangeRateFeeder;
  }
}
