/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEthAnchorConversionPool,
  IEthAnchorConversionPoolInterface,
} from "../../Fund.sol/IEthAnchorConversionPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "redeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IEthAnchorConversionPool__factory {
  static readonly abi = _abi;
  static createInterface(): IEthAnchorConversionPoolInterface {
    return new utils.Interface(_abi) as IEthAnchorConversionPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEthAnchorConversionPool {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IEthAnchorConversionPool;
  }
}
