/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Fund } from "./Fund";
export type { IERC20 } from "./IERC20";
export type { IERC721 } from "./IERC721";
export type { IEthAnchorConversionPool } from "./IEthAnchorConversionPool";
export type { IEthAnchorExchangeRateFeeder } from "./IEthAnchorExchangeRateFeeder";
export type { IUniswapV2Router01 } from "./IUniswapV2Router01";
